# Chapter 4: Linear Algebra

## What Is a Vector?
##### Example 4-1. Declaring a vector in Python using a list

In [1]:
v = [3, 2]
print(v)

[3, 2]


##### Example 4-2. Declaring a vector in Python using Numpy

In [1]:
# import numpy
import numpy as np

In [3]:
v = np.array([3, 2])
print(v)

[3 2]


##### Example 4-3. Declaring a three-dimensional vector in Python using Numpy

In [4]:
v = np.array([4, 1, 2])
print(v)

[4 1 2]


##### Example 4-4. Declaring a five-dimensional vector in Python using Numpy

In [5]:
v = np.array([6, 1, 5, 8, 3])
print(v)

[6 1 5 8 3]


#### Adding and Combining Vectors
##### Example 4-5. Adding two vectors in Python using Numpy

In [6]:
v = np.array([3, 2])
w = np.array([2, -1])

sum = v + w
print(sum)

[5 1]


### Scaling Vectors
##### Example 4-6. Scaling a number in Python using Numpy

In [8]:
v = np.array([3,1])

scaled_v = 2 * v

print(scaled_v)

[6 2]


## Linear Transformations
### Matrix Vector Multiplication
##### Example 4-7. Matrix vector mulitplication in Numpy

In [9]:
basis = np.array(
    [[3,0],
    [0,2]]
)

v = np.array([1, -1])

# dot product
new_v = basis.dot(v)
print(new_v)

[ 3 -2]


##### Example 4-8. Separating the basis vectors and applying them as a tranformation

In [11]:
# Declare i_hat & j_hat
i_hat = np.array([2,0])
j_hat = np.array([0,3])

basis = np.array([i_hat, j_hat]).transpose()

# Declare vector v
v = np.array([1,1])

new_v = basis.dot(v)

print(new_v)

[2 3]


##### Example 4-9. Transforming a vector using Numpy

In [3]:
i_hat = np.array([2,0])
j_hat = np.array([0,3])

basis = np.array([i_hat, j_hat]).transpose()

v = np.array([2,1])

new_v = basis.dot(v)

print(new_v)

[4 3]


##### Example 4-10. A more complicated tranformation

In [4]:
i_hat = np.array([2,3])
j_hat = np.array([2,-1])

basis = np.array([i_hat, j_hat]).transpose()

v = np.array([2,1])

new_v = basis.dot(v)

print(new_v)

[6 5]


## Matrix Multiplication
##### 4-11. Combining two transformations

In [6]:
# Tranformation 1
i_hat1 = np.array([0,1])
j_hat1 = np.array([-1,0])
transform1 = np.array([i_hat1, j_hat1]).transpose()

# Tranformation 2
i_hat2 = np.array([1,0])
j_hat2 = np.array([1,1])
transform2 = np.array([i_hat2, j_hat2]).transpose()

# Combine
combined = transform2 @ transform1

# Test
print(f'Combined Matrix:\n{combined}')

v = np.array([1,2])
print(combined.dot(v))

Combined Matrix:
[[ 1 -1]
 [ 1  0]]
[-1  1]


##### Example 4-12. Applying the transformations in reverse

In [3]:
# Tranformation 1
i_hat1 = np.array([0,1])
j_hat1 = np.array([-1,0])
transform1 = np.array([i_hat1, j_hat1]).transpose()

# Tranformation 2
i_hat2 = np.array([1,0])
j_hat2 = np.array([1,1])
transform2 = np.array([i_hat2, j_hat2]).transpose()

# Combine
combined = transform2 @ transform1

# Test
print(f'Combined Matrix:\n{combined}')

v = np.array([-2,3])
print(combined.dot(v))

Combined Matrix:
[[ 1 -1]
 [ 1  0]]
[-5 -2]


## Determinants
##### 4-13. Calculating a determinant

In [7]:
from numpy.linalg import det

i_hat = np.array([3,0])
j_hat = np.array([0,2])

basis = np.array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

6.0


##### Example 4-14. A determinant for a shear

In [8]:
i_hat = np.array([1,0])
j_hat = np.array([1,1])

basis = np.array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

1.0


##### Example 4-15. A negative determinant

In [9]:
i_hat = np.array([-2,1])
j_hat = np.array([1,2])

basis = np.array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

-5.000000000000001


##### Example 4-16. A determinant of zero

In [10]:
i_hat = np.array([-2,1])
j_hat = np.array([3,-1.5])

basis = np.array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

0.0


##### Example 4-17. Using SymPy to study the inverse and identity matrix

In [18]:
from sympy import *
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

inverse = A.inv()
identity = inverse * A

print(f'INVERSE: {inverse}')
print(f'IDENTITY: {identity}')

INVERSE: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
IDENTITY: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


##### Example 4-18. Using NumPy to solve system of equations

In [19]:
from numpy.linalg import inv
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = np.array([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])
B = np.array([
    44,
    56,
    72
])

x = inv(A).dot(B)

print(x)

[ 2. 34. -8.]


##### Example 4-19. Using SymPy to solve system of equations

In [20]:
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])
B = Matrix([
    44,
    56,
    72
])

x = A.inv() * B
print(x)

Matrix([[2], [34], [-8]])


##### Example 4-20. Performing eigendecompostion in NumPy

In [22]:
from numpy.linalg import eig

A = np.array([
    [1,2],
    [4,5]
])
eigenvals, eigenvecs = eig(A)

print('EIGEN VALUES')
print(eigenvals)

print('\nEIGEN VECTORS')
print(eigenvecs)

EIGEN VALUES
[-0.46410162  6.46410162]

EIGEN VECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


##### Example 4-21. Decomposing and recomposing a matrix in NumPy

In [23]:
A = np.array([
    [1,2],
    [4,5]
])
eigenvals, eigenvecs = eig(A)

print('EIGEN VALUES')
print(eigenvals)

print('\nEIGEN VECTORS')
print(eigenvecs)

print('\nREBUILD MATRIX')
Q = eigenvecs
R = inv(Q)

L = np.diag(eigenvals)
B = Q @ L @ R

print(B)

EIGEN VALUES
[-0.46410162  6.46410162]

EIGEN VECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]

REBUILD MATRIX
[[1. 2.]
 [4. 5.]]
