# Chapter 4: Linear Algebra

## What Is a Vector?
##### Example 4-1. Declaring a vector in Python using a list

In [1]:
v = [3, 2]
print(v)

[3, 2]


##### Example 4-2. Declaring a vector in Python using Numpy

In [2]:
# import numpy
import numpy as np

In [3]:
v = np.array([3, 2])
print(v)

[3 2]


##### Example 4-3. Declaring a three-dimensional vector in Python using Numpy

In [4]:
v = np.array([4, 1, 2])
print(v)

[4 1 2]


##### Example 4-4. Declaring a five-dimensional vector in Python using Numpy

In [5]:
v = np.array([6, 1, 5, 8, 3])
print(v)

[6 1 5 8 3]


#### Adding and Combining Vectors
##### Example 4-5. Adding two vectors in Python using Numpy

In [6]:
v = np.array([3, 2])
w = np.array([2, -1])

sum = v + w
print(sum)

[5 1]


### Scaling Vectors
##### Example 4-6. Scaling a number in Python using Numpy

In [8]:
v = np.array([3,1])

scaled_v = 2 * v

print(scaled_v)

[6 2]


## Linear Transformations
### Matrix Vector Multiplication
##### Example 4-7. Matrix vector mulitplication in Numpy

In [9]:
basis = np.array(
    [[3,0],
    [0,2]]
)

v = np.array([1, -1])

# dot product
new_v = basis.dot(v)
print(new_v)

[ 3 -2]


##### Example 4-8. Separating the basis vectors and applying them as a tranformation

In [11]:
# Declare i_hat & j_hat
i_hat = np.array([2,0])
j_hat = np.array([0,3])

basis = np.array([i_hat, j_hat]).transpose()

# Declare vector v
v = np.array([1,1])

new_v = basis.dot(v)

print(new_v)

[2 3]


##### Example 4-9. Transforming a vector using Numpy

In [3]:
i_hat = np.array([2,0])
j_hat = np.array([0,3])

basis = np.array([i_hat, j_hat]).transpose()

v = np.array([2,1])

new_v = basis.dot(v)

print(new_v)

[4 3]


##### Example 4-10. A more complicated tranformation

In [4]:
i_hat = np.array([2,3])
j_hat = np.array([2,-1])

basis = np.array([i_hat, j_hat]).transpose()

v = np.array([2,1])

new_v = basis.dot(v)

print(new_v)

[6 5]


## Matrix Multiplication
##### 4-11. Combining two transformations

In [6]:
# Tranformation 1
i_hat1 = np.array([0,1])
j_hat1 = np.array([-1,0])
transform1 = np.array([i_hat1, j_hat1]).transpose()

# Tranformation 2
i_hat2 = np.array([1,0])
j_hat2 = np.array([1,1])
transform2 = np.array([i_hat2, j_hat2]).transpose()

# Combine
combined = transform2 @ transform1

# Test
print(f'Combined Matrix:\n{combined}')

v = np.array([1,2])
print(combined.dot(v))

Combined Matrix:
[[ 1 -1]
 [ 1  0]]
[-1  1]


##### Example 4-12. Applying the transformations in reverse

In [7]:
# Tranformation 1
i_hat1 = np.array([0,1])
j_hat1 = np.array([-1,0])
transform1 = np.array([i_hat1, j_hat1]).transpose()

# Tranformation 2
i_hat2 = np.array([1,0])
j_hat2 = np.array([1,1])
transform2 = np.array([i_hat2, j_hat2]).transpose()

# Combine
combined = transform2 @ transform1

# Test
print(f'Combined Matrix:\n{combined}')

v = np.array([-2,3])
print(combined.dot(v))

Combined Matrix:
[[ 1 -1]
 [ 1  0]]
[-5 -2]
